name: Shulkerception
version: '${project.version}'
main: me.nick.shulkerception.ShulkerceptionPlugin
${plugin.api.declaration}
description: Put shulker boxes inside placed shulker boxes using vanilla clients.
author: '${plugin.author}'
